# Generated by Django 3.1.4 on 2020-12-03 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_auto_20201203_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='auth.user'),
            preserve_default=False,
        ),
    ]
