# Generated by Django 3.1.3 on 2020-11-24 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20201124_1659'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
