# Generated by Django 3.1.4 on 2020-12-11 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_auto_20201206_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='rating_count',
        ),
    ]
