# Generated by Django 3.1.4 on 2020-12-12 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_auto_20201211_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/Images/')),
                ('offer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.offers')),
            ],
        ),
    ]
